apiVersion: batch/v1
kind: CronJob
metadata:
  name: file-transfer-job
spec:
  schedule: {{ .Values.cronjob.schedule }}
  jobTemplate:
    spec:
      template:
        spec:
          {{- toYaml .Values.cronjob.spec | nindent 10 }}
